### ISSUE TITLE
레시피, 후기 수정 요청 사항

### ISSUE THREAD

**Issue by bella0413** [Animal-recipe/AnimalRecipe#21]
1. 레시피 폼 미입력 에러 났을 때 clean함수로 필드 에러 커스텀하기. 아니면 required 설정해서 필수입력 메세지 뜨게 하기.
2. 레시피 대표사진 없을 때 에러나는거 처리 → 위처럼 clean () 혹은 required로 해결
3. 레시피 입력 폼에서 step1까지만 만들어두기.  step2 입력 안하면 에러 나는 거 고치기
4. 레시피 디테일에서 레시피 타이틀 width 줄이기
5. 리뷰에서 사진 입력 안 했을 시 에러 화면 나는 거 고치기 → 위처럼 clean () 혹은 required로 해결
6. 리뷰에서 별 크기 달라서 누를 때마다 움직이는 거 고치기
7. <s>레시피 리스트 view에서 변수 관련 에러 나는 거 고치기. 레시피 중 하나 삭제 후 레시피 리스트 들어가려는데 이런 에러가 뜨더라구요. 확인 부탁드립니다. </s> -> 해결했습니다.
@Hongji0611 
```python
Internal Server Error: /mypage/myRecipe/
Traceback (most recent call last):
  File "C:\Users\dc200106\Desktop\AnimalRecipe\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dc200106\Desktop\AnimalRecipe\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dc200106\Desktop\AnimalRecipe\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dc200106\Desktop\AnimalRecipe\mypage\views.py", line 34, in myRecipe
    recipes_dict[myRecipes[i]] = img_obj.image.url
UnboundLocalError: local variable 'img_obj' referenced before assignment
[01/Jan/2021 05:35:08] "GET /mypage/myRecipe/ HTTP/1.1" 500 74209
Internal Server Error: /recipe/list/
Traceback (most recent call last):
  File "C:\Users\dc200106\Desktop\AnimalRecipe\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\dc200106\Desktop\AnimalRecipe\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\dc200106\Desktop\AnimalRecipe\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\dc200106\Desktop\AnimalRecipe\recipe\views.py", line 65, in recipe_list
    recipes_dict[recipes[i]] = img_obj.image.url
UnboundLocalError: local variable 'img_obj' referenced before assignment
```

**Comment by bella0413** [comment]
1. 레시피 폼의 필수 필드를 입력하지 않았을 때, 에러 위치 확인이 아직 미완성인 것 같습니다. 레시피 제목과 간단한 설명 필드는  required로 인한 메시지가 잘 뜨지만 그외 다른 필드들은 clean()이나 required가 미흡해보입니다. 각각의 필드들을 하나씩 비워가며 테스트해보시고 완성해주세요. 리뷰나 footer의 다른 필드들도 한번씩 점검 부탁드립니다.
2. 위에서 말한 모든 폼에서 placeholder와 실제 쓰는 인풋 텍스트의 색깔은 달라야하니 question의 폼을 참고해서 변경해주시길 바랍니다! 🙏
2. 후기에서 별 움직임이 아직 수정되지 않았습니다
3. 사진 없이 후기 다는 게 가능해졌지만 그럴 경우 사진이 안들어간채로 리스트에 보이는 게 아니라 특정 사진이 들어간 채로 보이네요. 그런데 디테일에 들어가면 또 그 특정 사진이 없는 채로 나옵니다. 괜찮으시다면 리스트나 디테일에서 빈 이미지란에 default image가 들어가는 게 좋을 것 같아요. 디자이너님께 부탁드려도 되고 그냥 '이미지가 없습니다.'라는 문구도 괜찮습니다! 많이 힘드시면 그냥 필수입력으로 바꾸셔도 괜찮습니다 (토닥토닥 무리하지 마요)
4. 레시피, 후기 리스트에서 4개 이하의 게시물 처리 로직을 추가해주세요. (베스트 게시물 관련 오류 수정) 그리고 레시피와 후기 리스트에서 아이템이 아예 없는 경우 질문 리스트와 같이 처리하도록 수정 부탁드립니다.
5. 작성하기, 취소하기 등등 지금까지 만드신 모든 버튼들의 그림자가 잘리지않도록 margin값을 조절해주시길 바랍니다.
6. 레시피 수정하기가 작동하지 않습니다 ㅠㅠ
7. 레시피, 후기 삭제 모달을 질문 카테고리 참고하여 만들어주시길 바랍니다. 디자인은 피그마 질문 페이지에 있어요!

레시피랑 후기 너무 예쁩니다!! 수고하셨어요😭👍❤
확인하시고 다음 PR에 모두 반영해주세요 @Hongji0611
